<a href="https://colab.research.google.com/github/aditi1295/MachineLearning/blob/main/Encoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Ordinal Encoding

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df=pd.read_csv('/content/customer.csv')

In [ ]:
df.sample(5)

    age gender   review education purchased
28   48   Male     Poor    School        No
21   32   Male  Average        PG        No
16   59   Male     Poor        UG       Yes
18   19   Male     Good    School        No
15   75   Male     Poor        UG        No

In [ ]:
df=df.iloc[:,2:]

In [ ]:
df.head()

    review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,0:2],df.iloc[:,-1], test_size=0.2)

In [ ]:
from sklearn.preprocessing import OrdinalEncoder

In [ ]:
oe=OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [ ]:
oe.fit(X_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [ ]:
X_train=oe.transform(X_train)

In [ ]:
X_train

array([[0., 1.],
       [0., 2.],
       [0., 0.],
       [2., 2.],
       [1., 1.],
       [2., 0.],
       [0., 1.],
       [1., 1.],
       [2., 0.],
       [1., 0.],
       [0., 2.],
       [0., 1.],
       [0., 0.],
       [2., 0.],
       [0., 2.],
       [2., 2.],
       [2., 0.],
       [0., 2.],
       [0., 0.],
       [1., 0.],
       [2., 1.],
       [2., 1.],
       [2., 0.],
       [1., 1.],
       [0., 2.],
       [1., 0.],
       [0., 2.],
       [0., 2.],
       [1., 2.],
       [2., 2.],
       [2., 2.],
       [1., 0.],
       [1., 1.],
       [1., 1.],
       [2., 1.],
       [2., 1.],
       [2., 1.],
       [0., 2.],
       [2., 0.],
       [1., 2.]])

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
le=LabelEncoder()

In [ ]:
le.fit(y_train)

LabelEncoder()

In [ ]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [ ]:
y_train=le.transform(y_train)
y_test=le.transform(y_test)

In [ ]:
y_train

array([0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1])

#One-Hot Encoding

In [ ]:
df=pd.read_csv('/content/cars.csv')

In [ ]:
df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [ ]:
df['brand'].value_counts()

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Land                6
Force               6
Isuzu               5
Ambassador          4
Kia                 4
MG                  3
Daewoo              3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

#One-Hot using Pandas

In [ ]:
pd.get_dummies(df,columns=['fuel','owner'])

,brand,km_driven,selling_price,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_First Owner,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,False,True,False,False,True,False,False,False,False
1,Skoda,120000,370000,False,True,False,False,False,False,True,False,False
2,Honda,140000,158000,False,False,False,True,False,False,False,False,True
3,Hyundai,127000,225000,False,True,False,False,True,False,False,False,False
4,Maruti,120000,130000,False,False,False,True,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,False,True,True,False,False,False,False
8124,Hyundai,119000,135000,False,True,False,False,False,True,False,False,False
8125,Maruti,120000,382000,False,True,False,False,True,False,False,False,False
8126,Tata,25000,290000,False,True,False,False,True,False,False,False,False
8127,Tata,25000,290000,False,True,False,False,True,False,False,False,False

#K-1 One-Hot

In [ ]:
pd.get_dummies(df,columns=['fuel','owner'],drop_first=True)

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,True,False,False,False,False,False,False
1,Skoda,120000,370000,True,False,False,False,True,False,False
2,Honda,140000,158000,False,False,True,False,False,False,True
3,Hyundai,127000,225000,True,False,False,False,False,False,False
4,Maruti,120000,130000,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,True,False,False,False,False
8124,Hyundai,119000,135000,True,False,False,True,False,False,False
8125,Maruti,120000,382000,True,False,False,False,False,False,False
8126,Tata,25000,290000,True,False,False,False,False,False,False
8127,Tata,25000,290000,True,False,False,False,False,False,False

#OneHot using Sklearn

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,0:4],df.iloc[:,-1],test_size=0.2,random_state=2)

In [ ]:

X_train.head()

         brand  km_driven    fuel         owner
5571   Hyundai      35000  Diesel   First Owner
2038      Jeep      60000  Diesel   First Owner
2957   Hyundai      25000  Petrol   First Owner
7618  Mahindra     130000  Diesel  Second Owner
6684   Hyundai     155000  Diesel   First Owner

In [ ]:

from sklearn.preprocessing import OneHotEncoder

In [ ]:
ohe=OneHotEncoder()

In [ ]:
X_train_new=ohe.fit_transform(X_train[['fuel','owner']]).toarray()

In [ ]:
X_test_new=ohe.transform(X_test[['fuel','owner']]).toarray()

In [ ]:
np.hstack((X_train[['brand','km_driven']].values,X_train_new)).shape

(6502, 11)

In [ ]:

pd.get_dummies(df['brand'].replace(repl, 'uncommon')).sample(5)

,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Renault,Tata,Toyota,Volkswagen,uncommon
5402,False,False,False,False,False,True,False,False,False,False,False
8086,False,False,False,False,False,True,False,False,False,False,False
2160,False,False,False,False,False,False,False,False,False,False,True
4115,False,True,False,False,False,False,False,False,False,False,False
7271,False,False,False,False,False,True,False,False,False,False,False

#One-Hot With Top Categories

In [ ]:
counts=df['brand'].value_counts()

In [ ]:
df['brand'].nunique()
threshold=180

In [ ]:
repl=counts[counts<=threshold].index

In [ ]:

pd.get_dummies(df['brand'].replace(repl, 'uncommon')).sample(5)

,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Renault,Tata,Toyota,Volkswagen,uncommon
4989,False,False,False,True,False,False,False,False,False,False,False
2983,False,False,False,False,True,False,False,False,False,False,False
216,False,False,False,False,False,False,False,False,True,False,False
312,False,False,True,False,False,False,False,False,False,False,False
5720,False,False,False,False,True,False,False,False,False,False,False